/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/groupomania_globe.glb");
  useFrame(({ clock }) => {
    group.current.rotation.x = clock.getElapsedTime();
    group.current.rotation.y = clock.getElapsedTime();
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Sphère.geometry}
        material={materials.Matériau}
        scale={[1.32, 1.32, 1.32]}
      />
      <mesh
        geometry={nodes.Sphère001.geometry}
        material={materials["Matériau.001"]}
        position={[-0.01, 0.02, 0]}
        scale={[1.33, 1.33, 1.33]}
      />
    </group>
  );
}

useGLTF.preload("/groupomania_globe.glb");
